# netlify.toml

# Define build settings for your Next.js project
[build]
  command = "npm run build"
  publish = ".next" # This is where Next.js outputs your built site

# No specific redirect for the form submission is needed here.
# Netlify will process POST requests to the form defined by name="contact-form"
# and redirect to the 'action' URL defined in your React form.

# Optional: If you want to explicitly redirect /thank-you to a specific file
# [[redirects]]
#   from = "/thank-you"
#   to = "/thank-you.html" # Or whatever path Next.js generates for your thank-you page
#   status = 200

# Optional: If you want to explicitly ignore the HTML forms processing for speed
# (though usually not necessary unless you have many forms or unusual behavior)
# [build.processing]
#   html = { forms = false }